image: node:22

stages:
     - test

cache:
    key:
        files:
            - package-lock.json
    paths:
        - node_modules/

web:
    stage: test
    script:
        - npm ci
        - npm run lint:web
        - npm run typecheck:web
        - npm run build:web
        
semgrep:
    stage: test
    image: semgrep/semgrep
    script: semgrep ci
    rules:
        - if: $CI_PIPELINE_SOURCE == "web"
        - if: $CI_MERGE_REQUEST_IID
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH