import embeddingsData from "../kb/embeddings.json";
import { embedTexts } from "./embeddings-client";

interface KbEmbedding {
  id:        string;
  title:     string;
  body:      string;
  embedding: number[];
}

export interface KbMatch {
  id:    string;
  title: string;
  body:  string;
  score: number;
}

function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot   += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

/**
 * Embeds `query` and returns the top-`topK` most similar KB articles by
 * cosine similarity against the pre-computed embeddings in kb/embeddings.json
 * (generated by scripts/embed.ts — run `npm run kb:embed` after editing kb/*.md).
 */
export async function retrieveRelevantArticles(
  query: string,
  topK = 3
): Promise<KbMatch[]> {
  const [queryEmbedding] = await embedTexts([query]);

  const scored: KbMatch[] = (embeddingsData as KbEmbedding[]).map((article) => ({
    id:    article.id,
    title: article.title,
    body:  article.body,
    score: cosineSimilarity(queryEmbedding, article.embedding),
  }));

  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, topK);
}
